on:
  push:
    tags:
      - v*.*.*

name: Deploy Prod

env:
  AUTH: ${{secrets.USER_DEPLOY_REPO}}:${{secrets.PERSONAL_ACCESS_TOKEN}}
  REPO: ${{secrets.DEPLOY_REPO}}
jobs:
  deploy_prod:
    strategy:
      matrix:
        go-version: [1.16.x]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Test
        run: go test -mod=vendor --race -v -coverprofile=coverage.out ./...
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
      - name: Deploy Prod
        run: |
          curl -XPOST -u "${AUTH}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" \
          https://api.github.com/repos/${REPO}/dispatches --data '{"event_type": "prod"}'
